pangeo-data/pangeo-datastore

.travis.yml

This upgrades the CI in this repo to use the latest `pangeo-notebook:2019-04-19` docker image from [pangeo-stacks](https://github.com/pangeo-data/pangeo-stacks/).
When I tested this image locally, it DID NOT WORK. The way I did this matches this repo's .travis.yml
```bash
export DOCKER_IMAGE=pangeo/pangeo-notebook:2019.04.19
docker pull $DOCKER_IMAGE
docker run -d --name pangeo $DOCKER_IMAGE
docker ps -a
```
On my laptop, the docker image dies immediately after the first `docker run` command.
I wonder if this error might have something to do with the big refactor that happened recently in pangeo-stacks.
cc @jhamman, @yuvipanda - do you have any idea why this is happening?

Upgrade to latest pangeo docker image 

---

README.md

The readme has become someout out of sync with the reality of what this repo has become. All of the discussion and links from the previous readme were pasted from various issues, so no info has been lost. The new readme is more focused towards datastore users.

update readme [ci skip]

---

intake-catalogs/ocean.yaml

This adds the ocean boundary flux fields for CM2.6.
cc @chiara7

add CM2.6 control boundary flux

---

intake-catalogs/atmosphere.yaml

The three dimensional fields (e.g. winds, humidity, and temperature) for this simulation were already in the catalog with the key  `sam_ngaqua_qobs_eqx_3d`. This commit also adds a catalog entry for two-dimensional variables (e.g. precipitation, top of atmosphere radiation), which I finally got around to uploading. 
I plotted the zonal+time mean of the data from hub.pangeo.io as a sanity check.

Add 2D variables from NG-Aqua CRM data

---

intake-catalogs/atmosphere.yaml

Update to GPM IMERG dataset:
- NASA included the TRMM-3B42RT era, which means GPM is now available from June 2000 instead of 2014.
- I added a version of the dataset that is primarily chunked in space, along with the time-chunked version.

GPM now chunked in time and space

---

docs/cmip6_catalog.rst
docs/conf.py
docs/index.rst

This adds an entry for the CMIP6 CSV catalog to the top level of Pangeo's data catalog; this allows users to browse the CSV file with all zarr store paths in a spreadsheet format, complete with the same sorting/filtering used by qgrid.

Add cmip6 CSV catalog

---

docs/cmip6_glade.rst
docs/cmip6_pangeo.rst
docs/conf.py
docs/index.rst

This adds a new page to the top directory of the Pangeo Datastore that gives a browser view of the GLADE catalog; next step is to consolidate these two pages under one parent page (which ideally provides some information about their purpose with regards to the hackathon), and then to parse through the associated JSON metadata for each catalog.

Added new catalog for GLADE

---

intake-catalogs/atmosphere.yaml
intake-catalogs/hydro.yaml
intake-catalogs/ocean.yaml
intake-catalogs/ocean/CESM_POP.yaml
intake-catalogs/ocean/GFDL_CM2.6.yaml
intake-catalogs/ocean/channel.yaml
intake-catalogs/ocean/llc4320.yaml

Changes the `urlpath` argument to reflect the new locations of the data, which is outlined [here](https://docs.google.com/spreadsheets/d/1X0zaHX2y1Cn6ki1BaiTqytmZFIeo8ovirJeBLCE554s/edit#gid=712653239).

Change urlpaths to reflect moved datasets

---

intake-catalogs/climate.yaml
intake-catalogs/master.yaml

We figured out how to embed ESM collection datasets in an existing intake catalog. Thanks for @jhamman for the help.
To load the collection:
```python
import intake
cat = intake.open_catalog('intake-catalogs/master.yaml')
esm_dstore = cat.climate.cmip6_gcs()
```
cc @andersy005

add CMIP6 and LENS catalogs

---

intake-catalogs/climate.yaml

Noticed that the non-raw Github link to JSON here was giving some problems with intake-esm.

Changed esmcol path from general Github link to raw

---

intake-catalogs/climate.yaml

In response to https://github.com/pangeo-data/pangeo-datastore/pull/75#discussion_r370192196, I asked around to see if there's any "official" identifier for CESM Large Ensemble dataset. It turns out that there isn't any (as far I can tell from the two responses I got).

Update CESM Large Ensemble identifier

---

intake-catalogs/ocean/GFDL_CM2.6.yaml

This should fix problems on the dynamic site and elsewhere - looks like the ocean budgets entry just needed an indent fix.

Fix indent issue with ocean budgets

---

intake-catalogs/ocean/GFDL_CM2.6.yaml
tests/test_datasets.py

This should hopefully ensure that we don't get a false success for improperly formatted Intake catalogs by calling `reload()`; I'm not sure if this is guaranteed to force Intake to load a YAML catalog, but if this doesn't work out our next best bet is `persist()`.

First attempt at updating dataset tests

---

intake-catalogs/atmosphere.yaml

Adding era5 hourly reanalysis (single levels) to pangeo athmophere catalog as _era5_hourly_reanalysis_single_levels_sa_. 
**sa** stands for spatial analysis to reflect how zarr chunks were optimized for spatial analysis rather than temporal analysis. This was added because there were conversations about eventually creating an era5 datasets chunked optimally for temporal analysis.

Adding era5 hourly reanalysis (single levels) to atmosphere catalog

---

intake-catalogs/climate.yaml

This adds a CM2.6 ESM collection to our climate catalog, with the collections specs themselves residing in Google's CMIP6 bucket.

Add entry for CM2.6 esm collection

---

intake-catalogs/ocean/GFDL_CM2.6.yaml

This updates the catalogs to point to a copy of GFDL's CM2.6 in Google's own CMIP6 bucket. If all goes well and the data is accessible there, the next step would be to remove this data from `gs://pangeo-gfdl-cm26`.

Update locations of CM2.6 data

---

tests/test_datasets.py

This will add a conditional to skip over parquet-based datasets for the time being, as the Docker image for pangeo-datastore does not have intake-parquet as a package. 
This is part of a larger issue with eventually fixing the CI of this repo to be able to access datasets in requester pays buckets, but this should at least allow for #86 to go through.

Add skipped case for parquet datasets

---

intake-catalogs/hydro.yaml

This should finish up the work of #61; noticed some issues when trying to open these datasets through the catalog site that may be a result of the anonymous credentials being used to access this data.

Remove anon token option from soil_grids

---

intake-catalogs/hydro.yaml
intake-catalogs/hydro/camels.yaml

These changes reflect the copying of NCAR Camels / SoilGrids to their own requester pays buckets, `gs://pangeo-ncar-camels` and `gs://pangeo-ncar-soilgrids`. 
Once this PR is merged and verified, we can begin removing the copies of the data in `gs://pangeo-data`.

Relocating NCAR Camels / SoilGrids

---

intake-catalogs/hydro.yaml
intake-catalogs/hydro/camels.yaml

Addresses the move of these datasets to requester pays buckets in #98.

Add requester_pays options to Camels and SoilGrids

---

intake-catalogs/ocean/channel.yaml

These additions to the channel catalog reflect the location of some data from `gs://pangeo-data` to `gs://pangeo-ldeo-mitgcm`, as outlined in #103. I don't have much knowledge of channel so would appreciate a review of the entry names and their descriptions!

Add entries to channel.yaml

---

intake-catalogs/ocean.yaml
intake-catalogs/ocean/MEOM-NEMO.yaml

This pull adds a MEOM-NEMO catalog to ocean.yaml, as discussed in #88.
Before this is merged, it looks like some of the datasets need to have their metadata consolidated. Additionally, I noticed there were two NATL60 SSH datasets in `gs://pangeo-meom` -- I included the second one as [NATL60_SSH_1](https://github.com/pangeo-data/pangeo-datastore/blob/e80350e8d91ffc5f158c1874c74df56591de47af/intake-catalogs/ocean/MEOM-NEMO.yaml#L63), but if there's a more descriptive name or if the entry is unnecessary I can change/remove it.

Add MEOM-NEMO catalog to ocean.yaml

---

README.md

This adds a step-by-step guide to setting up a billing project for use with requester pays data, courtesy of @agoodm, addressing issue #78.

Add requester pays instructions to README

---

intake-catalogs/climate.yaml

This adds the S3 mirrors of our GS data collections to the climate catalog.
I didn't change the names of any of the original entries so we can take some time to smoothly transition any resources that may have relied on the original URLs, but it might be good in the future to append `_gs` to those entries to make it clear who is hosting them.

Add data collections in S3 to climate catalog

---

README.md

The old intake syntax of `Catalog(url)` is deprecated. See #125

update README with latest intake syntax

---

intake-catalogs/atmosphere.yaml
intake-catalogs/hydro.yaml

This PR sets `consolidated: True` for Zarr datasets in our Intake catalogs, so that they can potentially be accessed by STAC Browser down the line.
Before this is merged, I would like to also consolidate the metadata for `hydro.nldas_hru_forcing` and `hydro.usgs_streamflow_observations`, which reside in S3 storage.

Use consolidated metadata for all Zarr datasets
