.travis.yml, intake-catalogs/atmosphere.yaml, intake-catalogs/hydro.yaml, intake-catalogs/master.yaml, intake-catalogs/ocean.yaml, tests/validate_datasets.py
This PR moves all of the known pangeo intake catalogs into this repo.
TODO:
cc @martindurant
=> put all intake catalogs here

.travis.yml, tests/test_imports.py
=> try to fix travis more

intake-catalogs/atmosphere.yaml
An example of how to add a dataset to the catalog. (And also a new dataset.)
=> add GPCP dataset

.travis.yml
this uses the latest pangeo-notebook image from pangeo-data/docker-stacks in CI
=> use latest image

intake-catalogs/atmosphere.yaml
=> remove newman entry

tests/validate_datasets.py
Some simplifications to the test code
=> clean up validation tests

.travis.yml, intake-catalogs/ocean.yaml, intake-catalogs/ocean/channel.yaml
This adds a couple of datasets from @roxyboy to the catalog.
=> add channel datasets

build_catalog_rst.py
=> use javascript friendly id in template

build_catalog_rst.py, docs/index.rst
- Don't try to print the full catalog hierarchy on the first page
- Use better titles
=> improve catalog formatting

intake-catalogs/ocean.yaml
This adds the NOAA NCEP Global Ocean Data Assimilation System dataset.
https://www.esrl.noaa.gov/psd/data/gridded/data.godas.html
This one would ideally be continuously updated. Need to figure out how to do that.
=> added godas

intake-catalogs/ocean.yaml, intake-catalogs/ocean/CESM_POP.yaml, intake-catalogs/ocean/GFDL_CM2.6.yaml, intake-catalogs/ocean/llc4320.yaml
I think all datasets with more than one intake entry should be nested.
=> increased nesting of ocean catalog

intake-catalogs/ocean/GFDL_CM2.6.yaml
=> add CM2.6 ocean_trans fields

intake-catalogs/ocean.yaml
This adds one of the orphaned datasets from the pangeo-data bucket to the catalog.
cc @gustavo-marques.
Here is the xarray repr of the dataset
```
<xarray.Dataset>
Dimensions:       (lath: 458, latq: 458, lonh: 540, lonq: 540, nv: 2, scalar_axis: 1, time: 24, xh: 540, xq: 540, yh: 458, yq: 458, z_i: 35, z_l: 34)
Coordinates:
geolat        (yh, xh) float64 dask.array<shape=(458, 540), chunksize=(458, 540)>
geolatb       (yq, xq) float64 dask.array<shape=(458, 540), chunksize=(458, 540)>
geolon        (yh, xh) float64 dask.array<shape=(458, 540), chunksize=(458, 540)>
geolonb       (yq, xq) float64 dask.array<shape=(458, 540), chunksize=(458, 540)>
* lath          (lath) float64 -79.2 -79.08 -78.95 ... 87.64 87.71 87.74
* latq          (latq) float64 -79.14 -79.01 -78.89 ... 87.68 87.73 …
```
=> add mom6-cesm

intake-catalogs/ocean/GFDL_CM2.6.yaml
Fixes https://github.com/pangeo-data/pangeo/issues/693
=> fix typo in CM2.6 catalog

intake-catalogs/atmosphere.yaml
Fixes #50. @davidbrochart - please open a new PR to re-add these datasets once they have been fixed.
=> remove gpm

docs/_static/jquery.json-viewer.css, docs/_static/jquery.json-viewer.js, docs/cmip6_glade.rst, docs/cmip6_pangeo.rst, docs/conf.py
This should give a nice JSON view of all the associated metadata for the CMIP6 catalogs. A preview can be viewed [here](https://charlesbluca.github.io/).
=> Added JSON viewer to CMIP6 catalog pages, added json-viewer dependencies

docs/cmip6_glade.rst, docs/cmip6_pangeo.rst
This addresses #56; feel free to use this PR as a place to request any other small formatting changes to the JSON/CSV view!
=> Added short blurb and link to ESMCol collection at top of page

intake-catalogs/ocean.yaml
This dataset contains the layers package output for ECCO and some variables like temperature in density coords.
=> Add layers package output for ECCO

intake-catalogs/atmosphere.yaml, intake-catalogs/cmip6_A3hr.yaml, intake-catalogs/cmip6_Omon.yaml, intake-catalogs/hydro.yaml, intake-catalogs/ocean.yaml, intake-catalogs/ocean/CESM_POP.yaml, intake-catalogs/ocean/GFDL_CM2.6.yaml, intake-catalogs/ocean/channel.yaml, intake-catalogs/ocean/llc4320.yaml
This is a necessary step toward moving these datasets to requester pays. 
cc @martinduran, @TomAugspurger, and @rabernat
=> remove storage options from catalogs

intake-catalogs/climate.yaml
This should add TRACMIP to the Climate catalog with a working ESM collection.
=> Add TRACMIP ESMCol to climate.yaml

.travis.yml, tests/validate_datasets.py
This will skip the test that actually opens the data. 
See https://github.com/pangeo-data/pangeo-datastore/pull/62#issuecomment-583499019
=> skip test to_dask

intake-catalogs/ocean/altimetry.yaml
This follows #58 and the switching of these datasets' containing bucket `gs://pangeo-cnes` to requester pays.
=> Remove anon token, add requester pays

intake-catalogs/ocean/channel.yaml
Add a dataset that shows float output from the channel run (and the corresponding 3-day-averaged model variables).
=> Add floats dataset

intake-catalogs/hydro.yaml
Adding data for streamflow prediction using deep learning to the "hydro" intake catalog
=> dl streamflow prediction data to catalog
